# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  main.show-banner: false
  security:
    basic.enabled: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/3l-diary
    username: sa
    password:
  jersey:
    type: filter
